-- ═════════════════════════════════════════════════════════════════════════════
-- VacunaTrack — 01_schema.sql
-- Definición completa del esquema de base de datos.
-- Contiene: creación de usuario/BD, extensiones, tipos ENUM y tablas.
-- Ejecutar como superusuario de PostgreSQL (postgres):
--   psql -U postgres -f 01_schema.sql
-- ═════════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────────
-- SECCIÓN 1: Creación de base de datos y usuario de aplicación
-- Ejecutar como superusuario (postgres)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE USER vacunatrack_user WITH PASSWORD '666' CREATEDB;
CREATE DATABASE vacunatrack OWNER vacunatrack_user;

\c vacunatrack

GRANT ALL ON SCHEMA public TO vacunatrack_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO vacunatrack_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO vacunatrack_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO vacunatrack_user;
SET ROLE vacunatrack_user;


-- ─────────────────────────────────────────────────────────────────────────────
-- SECCIÓN 2: Extensiones
-- ─────────────────────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ─────────────────────────────────────────────────────────────────────────────
-- SECCIÓN 3: Tipos enumerados (ENUMs)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TYPE tipo_sexo AS ENUM ('M','F');
CREATE TYPE tipo_dosis AS ENUM ('UNICA','SERIE_PRIMARIA','REFUERZO','ANUAL','ADICIONAL');
CREATE TYPE tipo_alerta_dosis AS ENUM ('APLICABLE','ATRASADA','CERCA_LIMITE','FALTANTE');
CREATE TYPE tipo_alerta_inv AS ENUM ('CERCA_AGOTAR','CERCA_CADUCAR','AGOTADO','CADUCADO');


-- ─────────────────────────────────────────────────────────────────────────────
-- SECCIÓN 4: Tablas en orden de dependencia
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- GEOGRAFÍA
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE paises (
    pais_id integer generated by default as identity primary key,
    pais_nombre varchar(100) not null unique
);

CREATE TABLE estados (
    estado_id integer generated by default as identity primary key,
    estado_nombre varchar(100) not null,
    pais_id integer not null,
    -- No se puede eliminar un país con estados registrados.
    FOREIGN KEY (pais_id) REFERENCES paises (pais_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ciudades (
    ciudad_id integer generated by default as identity primary key,
    ciudad_nombre varchar(100) not null,
    estado_id integer not null,
    FOREIGN KEY (estado_id) REFERENCES estados (estado_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CATÁLOGOS CLÍNICOS
-- ─────────────────────────────────────────────────────────────────────────────

-- vacuna_activa permite desactivar vacunas descontinuadas sin eliminar historial.
CREATE TABLE vacunas (
    vacuna_id integer generated by default as identity primary key,
    vacuna_nombre varchar(150) not null unique,
    vacuna_activa boolean not null default true
);

-- padecimiento_activo permite desactivar sin perder historial.
CREATE TABLE padecimientos (
    padecimiento_id integer generated by default as identity primary key,
    padecimiento_nombre varchar(150) not null unique,
    padecimiento_descripcion text,
    padecimiento_activo boolean not null default true
);

-- Tabla puente M:N — PK simple, sin dependencias parciales ni transitivas.
CREATE TABLE vacunas_padecimientos (
    vac_pad_id integer generated by default as identity primary key,
    vacuna_id integer not null,
    padecimiento_id integer not null,
    UNIQUE (vacuna_id, padecimiento_id),
    FOREIGN KEY (vacuna_id) REFERENCES vacunas (vacuna_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (padecimiento_id) REFERENCES padecimientos (padecimiento_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- esquema_vigente_desde / esquema_vigente_hasta permiten versionar el catálogo
-- sin reescribir decisiones clínicas históricas.
CREATE TABLE esquemas (
    esquema_id integer generated by default as identity primary key,
    esquema_nombre varchar(150) not null unique,
    esquema_fecha_vigencia date not null,
    esquema_vigente_desde date not null default current_date,
    esquema_vigente_hasta date,
    CHECK (esquema_vigente_hasta IS NULL OR esquema_vigente_hasta > esquema_vigente_desde)
);

-- dosis_vigente_desde / dosis_vigente_hasta permiten cambiar reglas clínicas
-- sin perder el historial de aplicaciones anteriores.
CREATE TABLE dosis (
    dosis_id integer generated by default as identity primary key,
    vacuna_id integer not null,
    dosis_tipo tipo_dosis not null,
    dosis_cant_ml numeric(5,2) not null CHECK (dosis_cant_ml > 0),
    dosis_area_aplicacion varchar(100) not null,
    dosis_edad_oportuna_dias integer not null CHECK (dosis_edad_oportuna_dias >= 0),
    dosis_intervalo_min_dias integer not null CHECK (dosis_intervalo_min_dias >= 0),
    dosis_limite_edad_dias integer CHECK (dosis_limite_edad_dias >= 0),
    dosis_vigente_desde date not null default current_date,
    dosis_vigente_hasta date,
    CHECK (dosis_vigente_hasta IS NULL OR dosis_vigente_hasta >= dosis_vigente_desde),
    -- No se puede eliminar una vacuna con dosis definidas.
    FOREIGN KEY (vacuna_id) REFERENCES vacunas (vacuna_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Tabla puente M:N — PK simple, sin dependencias parciales ni transitivas.
CREATE TABLE dosis_esquemas (
    dosis_esq_id integer generated by default as identity primary key,
    esquema_id integer not null,
    dosis_id integer not null,
    UNIQUE (esquema_id, dosis_id),
    -- Si se elimina el esquema, sus asociaciones a dosis desaparecen.
    FOREIGN KEY (esquema_id) REFERENCES esquemas (esquema_id) ON DELETE CASCADE ON UPDATE CASCADE,
    -- No se puede eliminar una dosis asignada a un esquema.
    FOREIGN KEY (dosis_id) REFERENCES dosis (dosis_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CENTROS DE SALUD
-- Se define antes que usuarios porque usuarios.centro_id la referencia.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE centros_salud (
    centro_id integer generated by default as identity primary key,
    centro_nombre varchar(150) not null,
    centro_calle varchar(150) not null,
    centro_numero varchar(10) not null,
    centro_codigo_postal varchar(10) not null,
    ciudad_id integer not null,
    centro_horario_inicio time not null,
    centro_horario_fin time not null,
    centro_latitud numeric(11,8) CHECK (centro_latitud BETWEEN -90 AND 90),
    centro_longitud numeric(11,8) CHECK (centro_longitud BETWEEN -180 AND 180),
    centro_telefono varchar(20) unique not null,
    centro_beacon varchar(100) unique,
    CHECK (centro_horario_fin > centro_horario_inicio),
    FOREIGN KEY (ciudad_id) REFERENCES ciudades (ciudad_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- USUARIOS Y AUTENTICACIÓN
-- ─────────────────────────────────────────────────────────────────────────────

-- Tabla unificada para todos los actores del sistema.
-- Atributos exclusivos de responsable son NULLables.
-- La validación de rol correcto en FKs externas se realiza en Flask.
CREATE TABLE usuarios (
    usuario_id integer generated by default as identity primary key,
    usuario_prim_nombre varchar(100) not null,
    usuario_seg_nombre varchar(100),
    usuario_apellido_pat varchar(100) not null,
    usuario_apellido_mat varchar(100),
    usuario_telefono varchar(20) not null unique,
    usuario_curp varchar(18) not null unique,
    -- Ruta relativa a static/, ej: 'img/usuarios/3.jpg'. NULL usa imagen por defecto.
    usuario_imagen varchar(255),
    usuario_activo boolean not null default true,
    -- Atributo exclusivo de administrador y/o responsable. NULL si no aplica.
    usuario_rfc varchar(13) unique,
    -- Atributo exclusivo de responsable. NULL si no aplica.
    centro_id integer,
    FOREIGN KEY (centro_id) REFERENCES centros_salud (centro_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Credenciales de acceso. Un usuario tiene un único correo y contraseña
-- independientemente de cuántos roles tenga.
CREATE TABLE login (
    login_id integer generated by default as identity primary key,
    usuario_id integer not null unique,
    login_correo varchar(150) not null unique,
    login_contrasena varchar(255) not null,
    -- Si se elimina el usuario, sus credenciales desaparecen.
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Catálogo de roles del sistema.
CREATE TABLE roles (
    rol_id integer generated by default as identity primary key,
    rol_nombre varchar(50) not null unique
);

-- Tabla puente M:N entre usuarios y roles.
-- Permite que un usuario tenga múltiples roles y que se agreguen roles nuevos
-- sin modificar la estructura de la tabla usuarios.
CREATE TABLE usuarios_roles (
    us_rol_id integer generated by default as identity primary key,
    usuario_id integer not null,
    rol_id integer not null,
    UNIQUE (usuario_id, rol_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (rol_id) REFERENCES roles (rol_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Cédulas profesionales de responsables médicos.
-- Requiere usuario con rol responsable (validado en Flask).
CREATE TABLE cedulas (
    cedula_id integer generated by default as identity primary key,
    cedula_numero varchar(50) not null unique,
    cedula_especialidad varchar(100),
    usuario_id integer not null,
    -- Si se elimina el usuario, sus cédulas desaparecen.
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- INVENTARIO
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE fabricantes (
    fabricante_id integer generated by default as identity primary key,
    fabricante_nombre varchar(150) not null,
    fabricante_telefono varchar(20) unique,
    pais_id integer not null,
    FOREIGN KEY (pais_id) REFERENCES paises (pais_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Persona física que realizó la venta del lote.
-- Permite identificar al vendedor en caso de incidente con una vacuna.
CREATE TABLE proveedores (
    proveedor_id integer generated by default as identity primary key,
    proveedor_prim_nombre varchar(100) not null,
    proveedor_seg_nombre varchar(100),
    proveedor_apellido_pat varchar(100) not null,
    proveedor_apellido_mat varchar(100),
    proveedor_email varchar(150) unique,
    proveedor_telefono varchar(20) unique,
    proveedor_empresa varchar(150),
    fabricante_id integer not null,
    -- No se puede eliminar un fabricante con proveedores registrados.
    FOREIGN KEY (fabricante_id) REFERENCES fabricantes (fabricante_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- fabricante_id y proveedor_id se guardan directamente en lotes aunque ya exista
-- relación entre sí, para congelar la información al momento del registro y
-- protegerla ante cambios futuros de asociación del proveedor.
CREATE TABLE lotes (
    lote_id integer generated by default as identity primary key,
    lote_codigo varchar(50) not null unique,
    lote_fecha_fabricacion date not null,
    lote_fecha_caducidad date not null,
    lote_cant_inicial integer not null CHECK (lote_cant_inicial > 0),
    vacuna_id integer not null,
    fabricante_id integer not null,
    proveedor_id integer not null,
    CHECK (lote_fecha_caducidad > lote_fecha_fabricacion),
    -- Trazabilidad legal: no se puede eliminar ninguno de estos actores con lotes registrados.
    FOREIGN KEY (vacuna_id) REFERENCES vacunas (vacuna_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (fabricante_id) REFERENCES fabricantes (fabricante_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (proveedor_id) REFERENCES proveedores (proveedor_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- inventario_activo_desde es NULL hasta que el responsable confirma la llegada.
-- usuario_id registra quién confirmó la llegada del inventario al centro.
CREATE TABLE inventarios (
    inventario_id integer generated by default as identity primary key,
    centro_id integer not null,
    lote_id integer not null,
    inventario_stock_inicial integer not null CHECK (inventario_stock_inicial >= 0),
    inventario_stock_actual integer not null CHECK (inventario_stock_actual >= 0),
    -- NULL hasta confirmación del responsable médico.
    inventario_activo_desde timestamp,
    -- NULL hasta confirmación. Requiere usuario con rol responsable (validado en Flask).
    usuario_id integer,
    -- NULL significa inventario original (llegó directo del proveedor).
    -- Con valor indica que es producto de una transferencia desde otro centro.
    inventario_origen_id integer,
    FOREIGN KEY (centro_id) REFERENCES centros_salud (centro_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (lote_id) REFERENCES lotes (lote_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (inventario_origen_id) REFERENCES inventarios (inventario_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Solo registra origen y destino. La trazabilidad completa se obtiene
-- cruzando con inventarios, lotes, centros_salud y usuarios.
CREATE TABLE transferencias_inventario (
    transf_id      integer generated by default as identity primary key,
    inv_origen_id  integer not null,
    inv_destino_id integer not null,
    transf_timestamp timestamp not null default now(),
    CHECK (inv_origen_id <> inv_destino_id),
    FOREIGN KEY (inv_origen_id)  REFERENCES inventarios (inventario_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (inv_destino_id) REFERENCES inventarios (inventario_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE alertas_inventario (
    alerta_inv_id integer generated by default as identity primary key,
    inventario_id integer not null,
    alerta_inv_tipo tipo_alerta_inv not null,
    alerta_inv_timestamp timestamp not null default current_timestamp,
    FOREIGN KEY (inventario_id) REFERENCES inventarios (inventario_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- PACIENTES
-- ─────────────────────────────────────────────────────────────────────────────

-- Política institucional: se requiere CURP o certificado de nacimiento (al menos uno).
CREATE TABLE pacientes (
    paciente_id integer generated by default as identity primary key,
    paciente_prim_nombre varchar(100) not null,
    paciente_seg_nombre varchar(100),
    paciente_apellido_pat varchar(100) not null,
    paciente_apellido_mat varchar(100),
    paciente_num_cert_nac varchar(50) unique,
    paciente_curp varchar(18) unique,
    paciente_fecha_nac date not null CHECK (paciente_fecha_nac <= current_date),
    paciente_sexo tipo_sexo not null,
    paciente_nfc varchar(100) unique,
    paciente_imagen varchar(255),
    esquema_id integer not null,
    CHECK (paciente_num_cert_nac IS NOT NULL OR paciente_curp IS NOT NULL),
    FOREIGN KEY (esquema_id) REFERENCES esquemas (esquema_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Tabla puente M:N — PK simple, sin dependencias parciales ni transitivas.
-- Requiere usuario con rol tutor (validado en Flask).
CREATE TABLE pacientes_tutores (
    pac_tut_id integer generated by default as identity primary key,
    paciente_id integer not null,
    tutor_id integer not null,
    UNIQUE (paciente_id, tutor_id),
    FOREIGN KEY (paciente_id) REFERENCES pacientes (paciente_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (tutor_id) REFERENCES usuarios (usuario_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Registra cada cambio de esquema de un paciente.
-- Permite consultas longitudinales y preserva el historial ante cambios del esquema nacional.
CREATE TABLE esquemas_pacientes (
    esq_pac_id integer generated by default as identity primary key,
    paciente_id integer not null,
    esquema_id integer not null,
    esq_pac_desde date not null default current_date,
    esq_pac_hasta date,
    esq_pac_motivo_cambio varchar(255),
    CHECK (esq_pac_hasta IS NULL OR esq_pac_hasta > esq_pac_desde),
    -- Integridad histórica: no eliminar paciente/esquema con historial clínico.
    FOREIGN KEY (paciente_id) REFERENCES pacientes (paciente_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (esquema_id) REFERENCES esquemas (esquema_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- OPERACIONES CLÍNICAS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE alertas_dosis_pacientes (
    alerta_dosis_pac_id integer generated by default as identity primary key,
    paciente_id integer not null,
    dosis_id integer not null,
    alerta_dosis_pac_tipo tipo_alerta_dosis not null,
    alerta_dosis_pac_timestamp timestamp not null default current_timestamp,
    FOREIGN KEY (paciente_id) REFERENCES pacientes (paciente_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (dosis_id) REFERENCES dosis (dosis_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Requiere usuario con rol tutor (validado en Flask).
CREATE TABLE lecturas_beacon (
    lectura_id integer generated by default as identity primary key,
    centro_id integer not null,
    tutor_id integer not null,
    lectura_timestamp timestamp not null default current_timestamp,
    FOREIGN KEY (centro_id) REFERENCES centros_salud (centro_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (tutor_id) REFERENCES usuarios (usuario_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Requiere usuario con rol tutor (validado en Flask).
CREATE TABLE eventos_gps (
    evento_id integer generated by default as identity primary key,
    tutor_id integer not null,
    evento_latitud numeric(11,8) not null CHECK (evento_latitud BETWEEN -90 AND 90),
    evento_longitud numeric(11,8) not null CHECK (evento_longitud BETWEEN -180 AND 180),
    evento_timestamp timestamp not null default current_timestamp,
    FOREIGN KEY (tutor_id) REFERENCES usuarios (usuario_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- centro_id y lote_id reemplazan inventario_id para permitir registro retroactivo.
-- La lógica de descuento de inventario se resuelve en Flask buscando el registro
-- en inventarios que corresponda a (centro_id, lote_id).
-- usuario_id y centro_id se guardan directamente para congelar la información:
-- si el responsable cambia de centro, la aplicación histórica no se altera.
-- Ninguna FK permite CASCADE DELETE: integridad histórica legal.
-- Requiere usuario con rol responsable (validado en Flask).
CREATE TABLE aplicaciones (
    aplicacion_id integer generated by default as identity primary key,
    paciente_id integer not null,
    usuario_id integer not null,
    centro_id integer not null,
    lote_id integer not null,
    dosis_id integer not null,
    -- Fecha y hora real de la aplicación (capturada por el responsable).
    aplicacion_timestamp timestamp not null,
    -- Fecha y hora en que se registró en el sistema (automático, no editable).
    aplicacion_registrado_en timestamp not null default current_timestamp,
    aplicacion_observaciones text,
    -- La aplicación no puede registrarse con fecha futura.
    CHECK (aplicacion_timestamp <= current_timestamp),
    FOREIGN KEY (paciente_id) REFERENCES pacientes (paciente_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (centro_id) REFERENCES centros_salud (centro_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (lote_id) REFERENCES lotes (lote_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (dosis_id) REFERENCES dosis (dosis_id) ON DELETE RESTRICT ON UPDATE CASCADE
);


-- ─────────────────────────────────────────────────────────────────────────────
-- SECCIÓN 5: Índices
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX idx_aplicaciones_paciente ON aplicaciones(paciente_id);
CREATE INDEX idx_aplicaciones_usuario ON aplicaciones(usuario_id,aplicacion_timestamp DESC);
CREATE INDEX idx_aplicaciones_timestamp ON aplicaciones(aplicacion_timestamp);
CREATE INDEX idx_aplicaciones_centro ON aplicaciones(centro_id);
CREATE INDEX idx_aplicaciones_lote ON aplicaciones(lote_id);
CREATE INDEX idx_alertas_dosis_pac_paciente ON alertas_dosis_pacientes(paciente_id);
CREATE INDEX idx_lote_codigo ON lotes(lote_codigo);
CREATE INDEX idx_lotes_proveedor ON lotes(proveedor_id);
CREATE INDEX idx_inventarios_centro ON inventarios(centro_id,inventario_activo_desde);
CREATE INDEX idx_inventarios_lote ON inventarios(lote_id);
CREATE INDEX idx_inventarios_origen ON inventarios(inventario_origen_id);
CREATE INDEX idx_transf_origen ON transferencias_inventario(inv_origen_id);
CREATE INDEX idx_transf_destino ON transferencias_inventario(inv_destino_id);
CREATE INDEX idx_alertas_inv_inventario ON alertas_inventario(inventario_id,alerta_inv_timestamp DESC);
CREATE INDEX idx_lecturas_beacon_centro ON lecturas_beacon(centro_id,lectura_timestamp DESC);
CREATE INDEX idx_eventos_gps_timestamp ON eventos_gps(evento_timestamp);
CREATE INDEX idx_pacientes_tutores_tutor ON pacientes_tutores(tutor_id);
CREATE INDEX idx_pacientes_tutores_paciente ON pacientes_tutores(paciente_id);
CREATE INDEX idx_esq_pac_paciente ON esquemas_pacientes(paciente_id);
CREATE INDEX idx_esq_pac_vigencia ON esquemas_pacientes(paciente_id,esq_pac_desde DESC);
CREATE INDEX idx_login_usuario ON login(usuario_id);
CREATE INDEX idx_usuarios_roles_usuario ON usuarios_roles(usuario_id);
CREATE INDEX idx_usuarios_roles_rol ON usuarios_roles(rol_id);
CREATE INDEX idx_proveedores_fabricante ON proveedores(fabricante_id);
